### ISSUE TITLE
GDLauncher not storing Resource Packs in the proper folder when included in modpacks. 

### ISSUE THREAD

**Issue by Gunner76th** [gorilla-devs/GDLauncher#538]
**Describe the bug**
When installing modpacks that include a Resource Pack, the pack archives are not being stored in the proper folder. For some reason GDLauncher is downloading and storing these resource packs in the mods folder instead of the resourcepacks folder like it should be. I have tested this modpack https://www.curseforge.com/minecraft/modpacks/engineers-life/files/2960009 in Twitch, ATLauncher, and MultiMC and they all download the resource packs to the proper folder. 

**To Reproduce**
Using GDLauncher, install the linked pack above (Engineer's Life 2.01)
Open the modpack's folder and open the resourcepacks folder, you will find it empty
Open the modpack's mods folder, and you will find 4 files in there that should not be, Dark_Loading_Screen.zip, Dark Modern GUIs - 1.0.2.zip, Unity-1.6.5-1.12-YABBandaid.zip, Unity-1.14.4-Dark-0.5.1.zip

**Expected behavior**
When installing modpacks that contain resource packs, those resource pack archives should be stored in the resourcepacks folder, NOT the mods folder.

**Possible solutions**
This seems to be a problem with the download stream methodology used by GDLauncher when pulling down and saving files from the Curseforge network. 

**Screenshots**
N/A

**Operating System:**

 - OS: Windows
 - Version: 10 Pro
- Launcher version: 1.0.6

**Additional context**

**Comment by ChaseIngebritson** [comment]
Tested on my end as well and can confirm that no resourcepack folder is generated and the resource packs are incorrectly stored in the mods folder.

**Operating System:**
* OS: Windows
* Version: 10 Pro
* Launcher version: 1.0.6

**Comment by TOLoneWolf** [comment]
would have been fixed by https://github.com/gorilla-devs/GDLauncher/pull/489 before 1.x.x was released.
(This also changes where native libs would be stored breaking any current instance installs for each mc version.)
https://github.com/gorilla-devs/GDLauncher/pull/489/commits/4c137db1f3e5b468f3e07d27fd5d4c55245466f9#diff-4a45b15b3529f15982d6d564223e0109R2110

**Comment by Gunner76th** [comment]
> would have been fixed by #489 before 1.x.x was released.
> (This also changes where native libs would be stored breaking any current instance installs for each mc version.)
> [4c137db#diff-4a45b15b3529f15982d6d564223e0109R2110](https://github.com/gorilla-devs/GDLauncher/commit/4c137db1f3e5b468f3e07d27fd5d4c55245466f9#diff-4a45b15b3529f15982d6d564223e0109R2110)

So is there any update on when this will be addressed and fix? Or was this fixed and not announced in the 1.0.8 update?

**Comment by janagyjr** [comment]
This still exists as a bug in 1.0.8, just installed a modpack that includes resourcepacks and the resourcepacks were put in the mod folder. I had to manually move them to the resourcepacks folder.

**Comment by Buggitt** [comment]
Still an issue on v1.0.9

Tested with the same modpack config zip. Twitch launcher puts the resource pack in resource pack folder, GDLauncher does not.
In addition to this, there is no way to browse resource packs in the launcher.

**Comment by Gunner76th** [comment]
> Still an issue on v1.0.9
> 
> Tested with the same modpack config zip. Twitch launcher puts the resource pack in resource pack folder, GDLauncher does not.
> In addition to this, there is no way to browse resource packs in the launcher.

Please do not try to hijack issues with unrelated reports. Please create a new issue tracker for your claimed issue of "In addition to this, there is no way to browse resource packs in the launcher." as that is a seperate and completely unrelated  issue.
