### ISSUE TITLE
Trouble Building on Arm64

### ISSUE THREAD

**Issue by theofficialgman** [gorilla-devs/GDLauncher#727]
**Describe the bug**
When attempting to build on arm64 (in this case a nintendo switch), the build fails.
Logs:
[2020-12-21T20_27_01_716Z-debug.log](https://github.com/gorilla-devs/GDLauncher/files/5726393/2020-12-21T20_27_01_716Z-debug.log)
[2020-12-21T20_27_01_772Z-debug.log](https://github.com/gorilla-devs/GDLauncher/files/5726394/2020-12-21T20_27_01_772Z-debug.log)
[2020-12-21T20_27_01_824Z-debug.log](https://github.com/gorilla-devs/GDLauncher/files/5726395/2020-12-21T20_27_01_824Z-debug.log)

**System:**
NVIDIA Jetson UNKNOWN
Jetpack 4.3 [L4T 32.3.1]
NV Power Mode: Locked_MAX - Type: 7
jetson_stats.service: active
Board info:
Type: UNKNOWN
SOC Family: tegra210 - ID:33
Module: UNKNOWN - Board: UNKNOWN
Code Name: icosa
Boardids: 2595:0000:A0
CUDA GPU architecture (ARCH_BIN): NONE
Serial Number: 1234
Libraries:
CUDA: NOT_INSTALLED
cuDNN: 7.6.3.28
TensorRT: 6.0.1.10
Visionworks: NOT_INSTALLED
OpenCV: 4.1.1 compiled CUDA: NO
VPI: NOT_INSTALLED
Vulkan: 1.1.70

 OS: Ubuntu 18.04.5 LTS aarch64 
Host: icosa 
Kernel: 4.9.140+ 
Shell: bash 4.4.20 
 DE: GNOME 3.28.4 
WM: GNOME Shell 
 Terminal: gnome-terminal 
CPU: (4) @ 1.989GHz 
Memory: 1429MiB / 3969MiB

**Comment by TOLoneWolf** [comment]
if I recall correctly to run the build you have to use a environment variable `RELEASE_TESTING=true` then `npm run release`

**Comment by theofficialgman** [comment]
hmm that doesn't seem to produce any better results

do note that this is my first time using node.js and rust so I could be doing something wrong in the process.

I'd be very appreciative if anyone could verify the readme build steps for me.

**Comment by Ladvace** [comment]
Try npm run build

**Comment by blarfoon** [comment]
@theofficialgman Could you provide your logs using `RELEASE_TESTING=true` in the `.env` file?

**Comment by theofficialgman** [comment]
logs are the exact same when adding that environment variable (export RELEASE_TESTING=true)

seems to be an issue with the build script for electron on arm64. note it can be done, as seen by https://github.com/SpacingBat3/electron-discord-webapp
which does work

**Comment by cobalt2727** [comment]
Gonna throw my two cents in. I'm trying to build on a Pi 4 Model B (yes, I know it won't perform well even if I get it built successfully). For starters, here's my system info:

OS: Ubuntu MATE 20.10 aarch64
Host: Raspberry Pi 4 Model B Rev 1.4
Kernel: 5.8.0-1011-raspi
Uptime: 2 hours, 32 mins 
Packages: 2707 (dpkg), 45 (flatpak) 
Shell: bash 5.0.17
DE: MATE 1.24.1
WM: Metacity (Marco)
Terminal: mate-terminal
CPU: BCM2835 (4) @ 1.500GHz
Memory: 1606MiB / 7631MiB

Worth mentioning I've correctly installed NodeJS, Rust, and Python correctly, as far as I'm aware. Also, the .env var RELEASE_TESTING was already set to true by default...

I had to make a few modifications to /GDLauncher/scripts/preinstall.js to get things going:
-set REQUIRED_NODE_VERSION to 'v14.15.4' to match my installed packages
-set REQUIRED_NODE_ARCH to 'arm64' for, well, obvious reasons

All my logs can be found attached
[2021-01-13T04_24_38_089Z-debug.log](https://github.com/gorilla-devs/GDLauncher/files/5806402/2021-01-13T04_24_38_089Z-debug.log)
[2021-01-13T04_24_38_154Z-debug.log](https://github.com/gorilla-devs/GDLauncher/files/5806403/2021-01-13T04_24_38_154Z-debug.log)
[2021-01-13T04_24_38_214Z-debug.log](https://github.com/gorilla-devs/GDLauncher/files/5806404/2021-01-13T04_24_38_214Z-debug.log)
[terminal_output.txt](https://github.com/gorilla-devs/GDLauncher/files/5806405/terminal_output.txt)

**Comment by AshtakaOOf** [comment]
hello you don't need to build GDLauncher i think you can just use the AppImage it will work fine and your raspberry 4 is one of the most powerful raspberry on the market

**Comment by cobalt2727** [comment]
> hello you don't need to build GDLauncher i think you can just use the AppImage it will work fine and your raspberry 4 is one of the most powerful raspberry on the market

The AppImage (and the deb) are x86_64 only. Also, the Pi 4 may have a good CPU but the GPU is way too weak to pull its own weight for games.

**Comment by NoozAbooz** [comment]
> The AppImage (and the deb) are x86_64 only. Also, the Pi 4 may have a good CPU but the GPU is way too weak to pull its own weight for games.

The GPU is fine sorta, it's the CPU which is limited. Seems like with some optimisations you can juice a 20 or 60 FPS out of it

**Comment by theofficialgman** [comment]
Update: I've been able to build GDLauncher successfully for arm64 (I think) but can't run it because of the precompiled murmur2.node and nsfw,node files included in this repo.

Could a dev (@killpowa) advise me how to go about building native versions of these required libraries? I think I need a proper `binding.gyp` file to do so in conjunction with using node-gyp

**Comment by theofficialgman** [comment]
@killpowa I apologize if this is a double ping. not sure if editing in a @ reference updates that person or not.

**Comment by theofficialgman** [comment]
oh I see.. this was the old repo where I can no longer get the source https://github.com/gorilla-devs/murmurhash32 ... thats not too nice
found a fork and can build from there with npm but that fork must have been out of date... because I just get this undefined symbol error now. or maybe I'm missing some dependencies on my install?
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot open /home/garrett/GDLauncher/release/linux-arm64-unpacked/resources/app.asar/build/native/linux/murmur2.node: Error: /home/garrett/GDLauncher/release/linux-arm64-unpacked/resources/app.asar/build/native/linux/murmur2.node: undefined symbol: _ZN2v811ArrayBuffer11GetContentsEv
    at Object.eval (webpack-internal:///./public/native/linux/murmur2.node:1:236)
    at eval (webpack-internal:///./public/native/linux/murmur2.node:2:30)
    at Object../public/native/linux/murmur2.node (/home/garrett/GDLauncher/release/linux-arm64-unpacked/resources/app.asar/build/electron.js:1:2217259)
    at t (/home/garrett/GDLauncher/release/linux-arm64-unpacked/resources/app.asar/build/electron.js:1:124)
    at eval (webpack-internal:///./public/native/murmur2.js:9:11)
    at Object../public/native/murmur2.js (/home/garrett/GDLauncher/release/linux-arm64-unpacked/resources/app.asar/build/electron.js:1:2219696)
    at t (/home/garrett/GDLauncher/release/linux-arm64-unpacked/resources/app.asar/build/electron.js:1:124)
    at eval (webpack-internal:///./public/electron.js:47:16)
    at Object../public/electron.js (/home/garrett/GDLauncher/release/linux-arm64-unpacked/resources/app.asar/build/electron.js:1:2170981)
    at t (/home/garrett/GDLauncher/release/linux-arm64-unpacked/resources/app.asar/build/electron.js:1:124)

```

**Comment by theofficialgman** [comment]
In my fork with the previous version of the buildfiles where natives are built instead of supplied as binaries, I get to this point and error out now
https://github.com/theofficialgman/GDLauncher
<pre>&gt; gdlauncher@1.1.8 postinstall
&gt; npm run rebuild


&gt; gdlauncher@1.1.8 rebuild
&gt; node ./scripts/buildNativeDeps.js

<span style="background-color:#2E3436"><font color="#06989A">neon</font></span> <span style="background-color:#2E3436"><font color="#555753">info</font></span> <font color="#555753">forcing rebuild for new build settings</font>
<span style="background-color:#2E3436"><font color="#06989A">neon</font></span> <span style="background-color:#2E3436"><font color="#555753">info</font></span> <font color="#555753">running cargo</font>
<font color="#8AE234"><b>   Compiling</b></font> memchr v2.3.3
<font color="#8AE234"><b>   Compiling</b></font> lazy_static v1.4.0
<font color="#8AE234"><b>   Compiling</b></font> regex-syntax v0.6.17
<font color="#8AE234"><b>   Compiling</b></font> cc v1.0.50
<font color="#8AE234"><b>   Compiling</b></font> autocfg v1.0.0
<font color="#8AE234"><b>   Compiling</b></font> cfg-if v0.1.10
<font color="#8AE234"><b>   Compiling</b></font> byteorder v1.3.4
<font color="#8AE234"><b>   Compiling</b></font> semver-parser v0.7.0
<font color="#8AE234"><b>   Compiling</b></font> cslice v0.2.0
<font color="#8AE234"><b>   Compiling</b></font> thread_local v1.0.1
<font color="#8AE234"><b>   Compiling</b></font> neon-build v0.3.3
<font color="#8AE234"><b>   Compiling</b></font> num-traits v0.2.11
<font color="#8AE234"><b>   Compiling</b></font> num-integer v0.1.42
<font color="#8AE234"><b>   Compiling</b></font> num-bigint v0.2.6
<font color="#8AE234"><b>   Compiling</b></font> semver v0.9.0
<font color="#8AE234"><b>   Compiling</b></font> aho-corasick v0.7.10
<font color="#8AE234"><b>   Compiling</b></font> murmurhash32 v0.2.0 (https://github.com/gorilla-devs/murmurhash32.git#40164089)
<font color="#8AE234"><b>   Compiling</b></font> regex v1.3.5
<font color="#8AE234"><b>   Compiling</b></font> neon-sys v0.3.3
The following warnings were emitted during compilation:

<font color="#FCE94F"><b>warning</b></font><b>:</b> ar: /home/garrett/GDLauncher/node_modules/murmur2-calculator/native/target/release/build/neon-sys-8b60283ae9b6e8be/out/native/build/Release/obj.target/neon/src/neon.o: No such file or directory

<font color="#EF2929"><b>error</b></font><b>:</b> failed to run custom build command for `neon-sys v0.3.3`

Caused by:
  process didn&apos;t exit successfully: `/home/garrett/GDLauncher/node_modules/murmur2-calculator/native/target/release/build/neon-sys-fa02a779a648ce32/build-script-build` (exit code: 1)
  --- stdout
  Skipping node-gyp installation as part of npm install.

  &gt; build-release
  &gt; node-gyp build

  make: Entering directory &apos;/home/garrett/GDLauncher/node_modules/murmur2-calculator/native/target/release/build/neon-sys-8b60283ae9b6e8be/out/native/build&apos;
    CXX(target) Release/obj.target/neon/src/neon.o
  neon.target.mk:109: recipe for target &apos;Release/obj.target/neon/src/neon.o&apos; failed
  make: Leaving directory &apos;/home/garrett/GDLauncher/node_modules/murmur2-calculator/native/target/release/build/neon-sys-8b60283ae9b6e8be/out/native/build&apos;
  TARGET = Some(&quot;aarch64-unknown-linux-gnu&quot;)
  HOST = Some(&quot;aarch64-unknown-linux-gnu&quot;)
  AR_aarch64-unknown-linux-gnu = None
  AR_aarch64_unknown_linux_gnu = None
  HOST_AR = None
  AR = None
  running: &quot;ar&quot; &quot;crs&quot; &quot;/home/garrett/GDLauncher/node_modules/murmur2-calculator/native/target/release/build/neon-sys-8b60283ae9b6e8be/out/libneon.a&quot; &quot;/home/garrett/GDLauncher/node_modules/murmur2-calculator/native/target/release/build/neon-sys-8b60283ae9b6e8be/out/native/build/Release/obj.target/neon/src/neon.o&quot;
  cargo:warning=ar: /home/garrett/GDLauncher/node_modules/murmur2-calculator/native/target/release/build/neon-sys-8b60283ae9b6e8be/out/native/build/Release/obj.target/neon/src/neon.o: No such file or directory
  exit code: 1

  --- stderr
  gyp info it worked if it ends with ok
  gyp info using node-gyp@3.6.2
  gyp info using node@15.14.0 | linux | arm64
  gyp info spawn make
  gyp info spawn args [ &apos;BUILDTYPE=Release&apos;, &apos;-C&apos;, &apos;build&apos; ]
  In file included from /home/garrett/.electron-gyp/13.1.0/include/node/node.h:67:0,
                   from ../node_modules/nan/nan.h:54,
                   from ../src/neon.cc:2:
  /home/garrett/.electron-gyp/13.1.0/include/node/v8.h:1670:79: warning: ?ResolveCallback? is deprecated [-Wdeprecated-declarations]
                                                         ResolveCallback callback);
                                                                                 ^
  /home/garrett/.electron-gyp/13.1.0/include/node/v8.h:8652:51: warning: ?HostImportModuleDynamicallyCallback? is deprecated [-Wdeprecated-declarations]
         HostImportModuleDynamicallyCallback callback);
                                                     ^
  In file included from ../node_modules/nan/nan.h:2884:0,
                   from ../src/neon.cc:2:
  ../node_modules/nan/nan_typedarray_contents.h: In constructor ?Nan::TypedArrayContents&lt;T&gt;::TypedArrayContents(v8::Local&lt;v8::Value&gt;)?:
  ../node_modules/nan/nan_typedarray_contents.h:34:43: error: ?class v8::ArrayBuffer? has no member named ?GetContents?; did you mean ?IsContext??
         data   = static_cast&lt;char*&gt;(buffer-&gt;GetContents().Data()) + byte_offset;
                                             ^~~~~~~~~~~
                                             IsContext
  In file included from ../src/neon.cc:10:0:
  ../src/neon_task.h: In member function ?void neon::Task::complete()?:
  ../src/neon_task.h:62:70: warning: ?v8::Local&lt;v8::Value&gt; node::MakeCallback(v8::Isolate*, v8::Local&lt;v8::Object&gt;, v8::Local&lt;v8::Function&gt;, int, v8::Local&lt;v8::Value&gt;*)? is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
       node::MakeCallback(isolate_, context-&gt;Global(), callback, 2, argv);
                                                                        ^
  In file included from ../node_modules/nan/nan.h:54:0,
                   from ../src/neon.cc:2:
  /home/garrett/.electron-gyp/13.1.0/include/node/node.h:192:50: note: declared here
                   NODE_EXTERN v8::Local&lt;v8::Value&gt; MakeCallback(
                                                    ^
  /home/garrett/.electron-gyp/13.1.0/include/node/node.h:108:42: note: in definition of macro ?NODE_DEPRECATED?
       __attribute__((deprecated(message))) declarator
                                            ^~~~~~~~~~
  ../src/neon.cc: In function ?size_t Neon_ArrayBuffer_Data(void**, v8::Local&lt;v8::ArrayBuffer&gt;)?:
  ../src/neon.cc:216:20: error: ?Contents? is not a member of ?v8::ArrayBuffer?
     v8::ArrayBuffer::Contents contents = buffer-&gt;GetContents();
                      ^~~~~~~~
  ../src/neon.cc:217:15: error: ?contents? was not declared in this scope
     *base_out = contents.Data();
                 ^~~~~~~~
  ../src/neon.cc:217:15: note: suggested alternative: ?hostent?
     *base_out = contents.Data();
                 ^~~~~~~~
                 hostent
  ../src/neon.cc: In function ?void Neon_Class_SetClassMap(v8::Isolate*, void*, Neon_DropCallback)?:
  ../src/neon.cc:328:41: warning: ?void node::AtExit(void (*)(void*), void*)? is deprecated: Use the three-argument variant of AtExit() or AddEnvironmentCleanupHook() [-Wdeprecated-declarations]
     node::AtExit(cleanup_class_map, holder);
                                           ^
  In file included from ../node_modules/nan/nan.h:54:0,
                   from ../src/neon.cc:2:
  /home/garrett/.electron-gyp/13.1.0/include/node/node.h:866:22: note: declared here
       NODE_EXTERN void AtExit(void (*cb)(void* arg), void* arg = nullptr));
                        ^
  /home/garrett/.electron-gyp/13.1.0/include/node/node.h:108:42: note: in definition of macro ?NODE_DEPRECATED?
       __attribute__((deprecated(message))) declarator
                                            ^~~~~~~~~~
  In file included from ../src/neon.cc:8:0:
  ../src/neon_string.h: In member function ?v8::Local&lt;v8::String&gt; neon::Slice::ToJsString(v8::Isolate*, const char*)?:
  ../src/neon_string.h:28:18: warning: ignoring return value of ?bool v8::MaybeLocal&lt;T&gt;::ToLocal(v8::Local&lt;S&gt;*) const [with S = v8::String; T = v8::String]?, declared with attribute warn_unused_result [-Wunused-result]
       maybe.ToLocal(&amp;result);
       ~~~~~~~~~~~~~^~~~~~~~~
  make: *** [Release/obj.target/neon/src/neon.o] Error 1
  gyp ERR! build error 
  gyp ERR! stack Error: `make` failed with exit code: 2
  gyp ERR! stack     at ChildProcess.onExit (/home/garrett/GDLauncher/node_modules/murmur2-calculator/native/target/release/build/neon-sys-8b60283ae9b6e8be/out/native/node_modules/node-gyp/lib/build.js:258:23)
  gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
  gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
  gyp ERR! System Linux 4.9.140+
  gyp ERR! command &quot;/usr/bin/node&quot; &quot;/home/garrett/GDLauncher/node_modules/murmur2-calculator/native/target/release/build/neon-sys-8b60283ae9b6e8be/out/native/node_modules/.bin/node-gyp&quot; &quot;build&quot;
  gyp ERR! cwd /home/garrett/GDLauncher/node_modules/murmur2-calculator/native/target/release/build/neon-sys-8b60283ae9b6e8be/out/native
  gyp ERR! node -v v15.14.0
  gyp ERR! node-gyp -v v3.6.2
  gyp ERR! not ok 


  error occurred: Command &quot;ar&quot; &quot;crs&quot; &quot;/home/garrett/GDLauncher/node_modules/murmur2-calculator/native/target/release/build/neon-sys-8b60283ae9b6e8be/out/libneon.a&quot; &quot;/home/garrett/GDLauncher/node_modules/murmur2-calculator/native/target/release/build/neon-sys-8b60283ae9b6e8be/out/native/build/Release/obj.target/neon/src/neon.o&quot; with args &quot;ar&quot; did not execute successfully (status code exit code: 1).


<span style="background-color:#2E3436"><font color="#06989A">neon</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> cargo build failed

Error: cargo build failed
    at Target.&lt;anonymous&gt; (/home/garrett/GDLauncher/node_modules/neon-cli/lib/target.js:98:27)
    at Generator.next (&lt;anonymous&gt;)
    at fulfilled (/home/garrett/GDLauncher/node_modules/neon-cli/lib/target.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
Installation failed.
/home/garrett/GDLauncher/node_modules/electron-build-env/index.js:8
  var err = new Error(msg);
            ^

Error: electron-build-env error
    at error (/home/garrett/GDLauncher/node_modules/<u style="text-decoration-style:single">electron-build-env</u>/index.js:8:13)
    at ChildProcess.&lt;anonymous&gt; (/home/garrett/GDLauncher/node_modules/<u style="text-decoration-style:single">electron-build-env</u>/index.js:117:16)
<font color="#555753">    at ChildProcess.emit (node:events:369:20)</font>
<font color="#555753">    at maybeClose (node:internal/child_process:1067:16)</font>
<font color="#555753">    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)</font> {
  cmd: <font color="#4E9A06">&apos;neon&apos;</font>,
  args: [ <font color="#4E9A06">&apos;build&apos;</font>, <font color="#4E9A06">&apos;murmur2-calculator&apos;</font>, <font color="#4E9A06">&apos;--release&apos;</font> ],
  opts: {
    stdio: <font color="#4E9A06">&apos;inherit&apos;</font>,
    env: {
      LESSOPEN: <font color="#4E9A06">&apos;| /usr/bin/lesspipe %s&apos;</font>,
      USER: <font color="#4E9A06">&apos;garrett&apos;</font>,
      LANGUAGE: <font color="#4E9A06">&apos;en_CA:en&apos;</font>,
      npm_config_user_agent: <font color="#4E9A06">&apos;npm/7.13.0 node/v15.14.0 linux arm64 workspaces/false&apos;</font>,
      TEXTDOMAIN: <font color="#4E9A06">&apos;im-config&apos;</font>,
      XDG_SEAT: <font color="#4E9A06">&apos;seat0&apos;</font>,
      SSH_AGENT_PID: <font color="#4E9A06">&apos;6642&apos;</font>,
      XDG_SESSION_TYPE: <font color="#4E9A06">&apos;x11&apos;</font>,
      npm_node_execpath: <font color="#4E9A06">&apos;/usr/bin/node&apos;</font>,
      LD_LIBRARY_PATH: <font color="#4E9A06">&apos;/usr/local/cuda-10.0/lib64&apos;</font>,
      SHLVL: <font color="#4E9A06">&apos;1&apos;</font>,
      RELEASE_TESTING: <font color="#4E9A06">&apos;true&apos;</font>,
      npm_config_noproxy: <font color="#4E9A06">&apos;&apos;</font>,
      QT4_IM_MODULE: <font color="#4E9A06">&apos;xim&apos;</font>,
      HOME: <font color="#4E9A06">&apos;/home/garrett&apos;</font>,
      DESKTOP_SESSION: <font color="#4E9A06">&apos;budgie-desktop&apos;</font>,
      npm_package_json: <font color="#4E9A06">&apos;/home/garrett/GDLauncher/package.json&apos;</font>,
      QT_STYLE_OVERRIDE: <font color="#4E9A06">&apos;&apos;</font>,
      npm_package_engines_node: <font color="#4E9A06">&apos;&gt;=14.16.0&apos;</font>,
      GTK_MODULES: <font color="#4E9A06">&apos;gail:atk-bridge&apos;</font>,
      MANAGERPID: <font color="#4E9A06">&apos;6090&apos;</font>,
      npm_config_userconfig: <font color="#4E9A06">&apos;/home/garrett/.npmrc&apos;</font>,
      DBUS_STARTER_BUS_TYPE: <font color="#4E9A06">&apos;session&apos;</font>,
      DBUS_SESSION_BUS_ADDRESS: <font color="#4E9A06">&apos;unix:path=/run/user/1000/bus,guid=e6703ad85e817fdb8f8c83e460bd4097&apos;</font>,
      npm_config_engine_strict: <font color="#4E9A06">&apos;true&apos;</font>,
      COLORTERM: <font color="#4E9A06">&apos;truecolor&apos;</font>,
      COLOR: <font color="#4E9A06">&apos;1&apos;</font>,
      npm_config_metrics_registry: <font color="#4E9A06">&apos;https://registry.npmjs.org/&apos;</font>,
      QT_QPA_PLATFORMTHEME: <font color="#4E9A06">&apos;gtk2&apos;</font>,
      IM_CONFIG_PHASE: <font color="#4E9A06">&apos;2&apos;</font>,
      LOGNAME: <font color="#4E9A06">&apos;garrett&apos;</font>,
      GTK_IM_MODULE: <font color="#4E9A06">&apos;ibus&apos;</font>,
      JOURNAL_STREAM: <font color="#4E9A06">&apos;8:22894&apos;</font>,
      _: <font color="#4E9A06">&apos;/usr/bin/npm&apos;</font>,
      npm_config_prefix: <font color="#4E9A06">&apos;/usr&apos;</font>,
      USERNAME: <font color="#4E9A06">&apos;garrett&apos;</font>,
      XDG_SESSION_ID: <font color="#4E9A06">&apos;1&apos;</font>,
      TERM: <font color="#4E9A06">&apos;xterm-256color&apos;</font>,
      npm_config_cache: <font color="#4E9A06">&apos;/home/garrett/.npm&apos;</font>,
      GNOME_DESKTOP_SESSION_ID: <font color="#4E9A06">&apos;this-is-deprecated&apos;</font>,
      WINDOWPATH: <font color="#4E9A06">&apos;1&apos;</font>,
      npm_config_node_gyp: <font color="#4E9A06">&apos;/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js&apos;</font>,
      PATH: <font color="#4E9A06">&apos;/home/garrett/GDLauncher/node_modules/.bin:/home/garrett/node_modules/.bin:/home/node_modules/.bin:/node_modules/.bin:/usr/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/home/garrett/GDLauncher/node_modules/.bin:/home/garrett/node_modules/.bin:/home/node_modules/.bin:/node_modules/.bin:/usr/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/usr/local/cuda-10.0/bin:/home/garrett/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/garrett/.local/bin&apos;</font>,
      INVOCATION_ID: <font color="#4E9A06">&apos;f90288d9a9b148548509f1cb78848439&apos;</font>,
      SESSION_MANAGER: <font color="#4E9A06">&apos;local/garrett-usb:@/tmp/.ICE-unix/6467,unix/garrett-usb:/tmp/.ICE-unix/6467&apos;</font>,
      NODE: <font color="#4E9A06">&apos;/usr/bin/node&apos;</font>,
      npm_package_name: <font color="#4E9A06">&apos;gdlauncher&apos;</font>,
      XDG_MENU_PREFIX: <font color="#4E9A06">&apos;gnome-&apos;</font>,
      GNOME_TERMINAL_SCREEN: <font color="#4E9A06">&apos;/org/gnome/Terminal/screen/6f648233_4be2_435a_881b_48ed6be0fe71&apos;</font>,
      XDG_RUNTIME_DIR: <font color="#4E9A06">&apos;/run/user/1000&apos;</font>,
      DISPLAY: <font color="#4E9A06">&apos;:0&apos;</font>,
      ZEITGEIST_DATA_PATH: <font color="#4E9A06">&apos;/home/garrett/.local/share/zeitgeist&apos;</font>,
      LANG: <font color="#4E9A06">&apos;en_CA.UTF-8&apos;</font>,
      XDG_CURRENT_DESKTOP: <font color="#4E9A06">&apos;Budgie:GNOME&apos;</font>,
      LS_COLORS: <font color="#4E9A06">&apos;rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:&apos;</font>,
      XDG_SESSION_DESKTOP: <font color="#4E9A06">&apos;budgie-desktop&apos;</font>,
      XMODIFIERS: <font color="#4E9A06">&apos;@im=ibus&apos;</font>,
      GNOME_TERMINAL_SERVICE: <font color="#4E9A06">&apos;:1.98&apos;</font>,
      XAUTHORITY: <font color="#4E9A06">&apos;/run/user/1000/gdm/Xauthority&apos;</font>,
      npm_lifecycle_script: <font color="#4E9A06">&apos;node ./scripts/buildNativeDeps.js&apos;</font>,
      SSH_AUTH_SOCK: <font color="#4E9A06">&apos;/run/user/1000/keyring/ssh&apos;</font>,
      SHELL: <font color="#4E9A06">&apos;/bin/bash&apos;</font>,
      npm_package_version: <font color="#4E9A06">&apos;1.1.8&apos;</font>,
      npm_lifecycle_event: <font color="#4E9A06">&apos;rebuild&apos;</font>,
      QT_ACCESSIBILITY: <font color="#4E9A06">&apos;1&apos;</font>,
      GDMSESSION: <font color="#4E9A06">&apos;budgie-desktop&apos;</font>,
      LESSCLOSE: <font color="#4E9A06">&apos;/usr/bin/lesspipe %s %s&apos;</font>,
      TEXTDOMAINDIR: <font color="#4E9A06">&apos;/usr/share/locale/&apos;</font>,
      GPG_AGENT_INFO: <font color="#4E9A06">&apos;/run/user/1000/gnupg/S.gpg-agent:0:1&apos;</font>,
      XDG_VTNR: <font color="#4E9A06">&apos;1&apos;</font>,
      QT_IM_MODULE: <font color="#4E9A06">&apos;ibus&apos;</font>,
      npm_config_globalconfig: <font color="#4E9A06">&apos;/usr/etc/npmrc&apos;</font>,
      npm_config_init_module: <font color="#4E9A06">&apos;/home/garrett/.npm-init.js&apos;</font>,
      PWD: <font color="#4E9A06">&apos;/home/garrett/GDLauncher&apos;</font>,
      npm_execpath: <font color="#4E9A06">&apos;/usr/lib/node_modules/npm/bin/npm-cli.js&apos;</font>,
      CLUTTER_IM_MODULE: <font color="#4E9A06">&apos;xim&apos;</font>,
      XDG_DATA_DIRS: <font color="#4E9A06">&apos;/usr/share/budgie-desktop:/home/garrett/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop&apos;</font>,
      DBUS_STARTER_ADDRESS: <font color="#4E9A06">&apos;unix:path=/run/user/1000/bus,guid=e6703ad85e817fdb8f8c83e460bd4097&apos;</font>,
      XDG_CONFIG_DIRS: <font color="#4E9A06">&apos;/etc/xdg/xdg-budgie-desktop:/etc/xdg&apos;</font>,
      npm_command: <font color="#4E9A06">&apos;run-script&apos;</font>,
      VTE_VERSION: <font color="#4E9A06">&apos;5202&apos;</font>,
      INIT_CWD: <font color="#4E9A06">&apos;/home/garrett/GDLauncher&apos;</font>,
      EDITOR: <font color="#4E9A06">&apos;vi&apos;</font>,
      npm_config_target: <font color="#4E9A06">&apos;13.1.0&apos;</font>,
      npm_config_arch: <font color="#4E9A06">&apos;arm64&apos;</font>,
      npm_config_target_arch: <font color="#4E9A06">&apos;arm64&apos;</font>,
      npm_config_disturl: <font color="#4E9A06">&apos;https://atom.io/download/electron&apos;</font>,
      npm_config_runtime: <font color="#4E9A06">&apos;electron&apos;</font>,
      npm_config_build_from_source: <font color="#C4A000">true</font>,
      npm_config_devdir: <font color="#4E9A06">&apos;/home/garrett/.electron-gyp&apos;</font>
    },
    shell: <font color="#C4A000">true</font>
  },
  stderr: <font color="#4E9A06">&apos;&apos;</font>
}
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">code</font> 1
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">path</font> /home/garrett/GDLauncher
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> command failed
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">command</font> sh -c npm run rebuild

<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> A complete log of this run can be found in:
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span>     /home/garrett/.npm/_logs/2021-06-07T04_04_12_071Z-debug.log
</pre>

**Comment by theofficialgman** [comment]
@killpowa I'd appreciate your input on this, I realize you are probably very busy and this is low priority as arm64 isn't officially supported by mojang even now.
https://github.com/gorilla-devs/GDLauncher/issues/727#issuecomment-854377002
all I need help with is these two depends and then I should be able to launch and see if other issues arise

**Comment by nicholasaiello** [comment]
@theofficialgman try this _POC branch_, https://github.com/nicholasaiello/GDLauncher/tree/arm64-updates

i rebuilt those two dependencies in Raspberry Pi OS (64-bit), and made other changes to the build scripts in order to support arm64. the launcher runs fine, and i'm able to play all versions, pre 1.17.x

here's how i built and ran the launcher (after `npm i`)
```sh
$ npm run release:setup
$ ./deploy/GDLauncher-linux-setup.AppImage
```
assuming that java is setup, and you have lwjgl3arm64, then you should be good to go

**Comment by cobalt2727** [comment]
So I've decided to melt my raspberry pi tonight by testing this out and I can confirm it builds (Ubuntu MATE 21.04, NodeSource LTS 14.something, Pi 4B 8GB)

I've got openjdk 16 installed so I'll give 1.17 a go and see if it launches in a moment

![Screenshot at 2021-07-26 00-37-02](https://user-images.githubusercontent.com/60624944/126938601-357cd26d-d2ac-4621-b721-78614d536d41.png)

**Comment by nicholasaiello** [comment]
@cobalt2727 thanks for trying it. any luck running 1.17.x? the issues that i ran into (re: 1.17.x releases) seemed to be caused by my java configuration, and AFAIK i'm using openjdk 11... i ran this script (found it on the Pi forums), in order to setup my java environment, and lwjgl libs: https://github.com/mikehooper/Minecraft/raw/main/setupMC.sh. otherwise, the launcher itself appeared to be working fine

**Comment by theofficialgman** [comment]
minecraft 1.17.x requires java 16 now, so openjdk 11 just won't work
I have a nintendo switch running linux, will test on this later today/tomorrow
Since your branch itself doesn't detail how to compile those couple of binaries, I'd really appreciate you documenting how you did so.

**Comment by cobalt2727** [comment]
-fresh purge and reinstall of NodeJS from nodesource LTS because I hate npm packages and everything was broken until I did a fresh start

-git clone; cd GDLauncher

-npm i

-npm run dev

**Comment by cobalt2727** [comment]
> @cobalt2727 thanks for trying it. any luck running 1.17.x? the issues that i ran into (re: 1.17.x releases) seemed to be caused by my java configuration, and AFAIK i'm using openjdk 11... i ran this script (found it on the Pi forums), in order to setup my java environment, and lwjgl libs: https://github.com/mikehooper/Minecraft/raw/main/setupMC.sh. otherwise, the launcher itself appeared to be working fine

I pulled from that script to set up lwjgl as well on my pi, GDLauncher didn't seem to open my 1.17 Fabric modpack instance despite me setting my java to Ubuntu's openJDK 16 manually... I only tried 1.17 before I signed off for the night, but I can try 1.16 this evening

**Comment by theofficialgman** [comment]
@nicholasaiello for one, you can't just setup your lwjgl binaries using that script and expect it to work
you need to tell gdlauncher the location of them so that they will work

I get the same error as cobalt when trying to open the command window to view the logs
i attempted to pass a custom library folder location to gdlauncher but it doesn't seem to do anything `-Djava.library.path=`

**Comment by cobalt2727** [comment]
I don't think I properly set up lwjgl, come to think of it. I'll make sure that's working next time I test

**Comment by theofficialgman** [comment]
you can view the log inside the instances folder in gdlauncher_next
unfortunatly regardless of what I do with -Djava.library.path= or -Dorg.lwjgl.librarypath I still get the error saying that lwjgl failed to load libraries
```
[09:59:37] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[09:59:37] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[09:59:37] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
```
I imagine that gdlauncher is dropping those commands from the jvm arguements I guess... just like the other launchers

**Comment by nicholasaiello** [comment]
> @nicholasaiello for one, you can't just setup your lwjgl binaries using that script and expect it to work
> you need to tell gdlauncher the location of them so that they will work
> 
> I get the same error as cobalt when trying to open the command window to view the logs
> i attempted to pass a custom library folder location to gdlauncher but it doesn't seem to do anything `-Djava.library.path=`

no expectations for the script to handle everything. just stating what i used to install those binaries. configuring the launcher is another thing. in order to point to said binaries, i added the following to the launcher's java args:
```
-Dorg.lwjgl.librarypath=/home/pi/lwjgl3arm64
```
here's an image of the Pi running MC Vanilla 1.16.5, from this past Sunday. 
![image](https://user-images.githubusercontent.com/256006/127196391-9e4e4835-cd03-4ec6-adbe-6da66caca7d3.png)

back to the original issue, if people are able to build on arm64 platforms, that's a positive. any trouble after that, mainly around configuration, could be solved with additional documentation. i could compile the commands that i used in to a gist if the maintainers think it'd be useful. @Ladvace @killpowa thoughts?

**Comment by cobalt2727** [comment]
I know some distros don't have Java 16 available as the default, or even available in the normal repositories yet (looking at you, Debian), so it could be nice if GDLauncher shipped with aarch64/armhf Java binaries. Could probably just borrow them from AdoptOpenJDK or something, I'm not familiar with any licensing issues there

**Comment by theofficialgman** [comment]
oh wait.. do all the .jar files have to be in one folder when you load with  -Dorg.lwjgl.librarypath? I was using the MultiMC standard where the libraries are sorted into subfolders based on type and version..
I'll need to try with all the jar files in one folder later today. hopefully thats my problem
I can also just try the pi binaries as well.. not sure what those were compiled against but they might work as well
currently I just get binares from luckchambers or JJTech0130

**Comment by theofficialgman** [comment]
@nicholasaiello I can confirm it was the formatting of the folder and binary file type that it didn't like. I was able to load minecraft with the binaries from mikehooper even though I got a lot of these errors in the log 
```
[17:08:23] [Render thread/INFO]: [STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
```

I'm not quite sure how all the file types are interlinked, because my MultiMC5 meta repo pulls only .jar files, while the code you linked (mikehooper) has both .so and .jar files, and then we have lukechambers mcswitchtools which only supplies .so files

the latter two, mikehooper and luke chambers expect you to load the binaries with -Dorg.lwjgl.librarypath
multimc5 has its own library loading mechanism

**Comment by theofficialgman** [comment]
also I can confirm minecraft 1.17.1 works just fine with a java 16 binary selected
I'm using the binaries found here https://gitlab.com/devluke/mcswitchtools/-/tree/master/MCSwitchTools/natives/3
there are lwjgl3 and 2 versions for arm64 and using them with the -Dorg.lwjgl.librarypath option

**Comment by theofficialgman** [comment]
@nicholasaiello would you mind walking through how you were able to build the murmur2-arm64.node and nsfw-arm64.node  binaries? so its documented and so I can repeat in the future as needed

**Comment by cobalt2727** [comment]
seconded

**Comment by Eskaan** [comment]
So @theofficialgman is it resolved?
We also released a new release whit Java 16 support, that could cause trouble from what I read here

**Comment by theofficialgman** [comment]
@Code-Ac No this is not resolved. the official GDLauncher will never build on arm64 until the changes are implemented from the @nicholasaiello fork/branch in a universal way to allow arm64 and x86_64 building. currently the gdlauncher contains x86_64 binaries for a couple of libraries which will cause any other architecture type to fail building among other small issues

**Comment by Eskaan** [comment]
Okay, thanks

**Comment by nicholasaiello** [comment]
> @nicholasaiello would you mind walking through how you were able to build the murmur2-arm64.node and nsfw-arm64.node binaries? so its documented and so I can repeat in the future as needed

apologies for the late response, all. i would not mind, and will try to get some simple instructions together in a gist (or two) — just need to pull the commands from that particular RPi4's SSD. `nsfw` built just fine w/ `node-gyp` (using `nvm` to run the latest LTS Node.js 14.17.x). there were some build issues w/ `murmur2` that required small changes... a one-line change to the header file, and maybe a couple changes to the `sconstruct` file (need to check the SSD) — there's probably a better way to do this, though. i've had limited bandwidth lately, so will need a few days to turn this around

**Comment by blarfoon** [comment]
Guys YOU ARE INSANE! Dropping ARM64 support (and possibly x32) was one of my goals for the future. Please contact me on discord I'd love to collaborate with you on this!

**Comment by JJTech0130** [comment]
> @nicholasaiello I can confirm it was the formatting of the folder and binary file type that it didn't like. I was able to load minecraft with the binaries from mikehooper even though I got a lot of these errors in the log
> 
> ```
> [17:08:23] [Render thread/INFO]: [STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
> Possible reasons:
> 	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
> 	b) The classpath contains jar files of an older LWJGL version.
> Possible solutions:
> 	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
> 	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
> 	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
> ```
> 
> I'm not quite sure how all the file types are interlinked, because my MultiMC5 meta repo pulls only .jar files, while the code you linked (mikehooper) has both .so and .jar files, and then we have lukechambers mcswitchtools which only supplies .so files
> 
> the latter two, mikehooper and luke chambers expect you to load the binaries with -Dorg.lwjgl.librarypath multimc5 has its own library loading mechanism

@theofficialgman 
IIRC the .jars are simply zips containing the .so ... I have a script to generate it around here somewhere...

**Comment by theofficialgman** [comment]
yes I know.... I've made the .jar files myself already (you can see them on my github)
the problem is there its not trivial to get gdlauncher to automate loading replacement jars (without asking the user which version of lwjgl is really needed). there isn't any scripting support within gdlauncher to hotpatch in separate libraries, and use java arguments isn't a workable solution either since it would need the change per instance/version of minecraft

**Comment by theofficialgman** [comment]
@JJTech0130 your response was to stupid past me from months ago. I didn't understand at the time but am much better educated and knowledgeable now

**Comment by JJTech0130** [comment]
Ah. Do you know of any alternative launchers that actually work on the pi (other than MMC)? I'm looking for a friend who wants something more modern and user friendly than MMC)-- that's how I stumbled upon this issue 😆

**Comment by theofficialgman** [comment]
the lunar client decompilation project from pi-labs is an OK solution if you don't care about older minecraft versions... but its more a hack than anything and I doubt it will be kept up to date very well

otherwise thats it... though MMC isn't THAT bad (I know we are a bit biased but thats what I would recommend)

**Comment by JJTech0130** [comment]
Ok... I use it myself but the older-style ui scared my friend away... will try and convince them :)

**Comment by theofficialgman** [comment]
```
[17:08:23] [Render thread/INFO]: [STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
```
fyi: these errors that I reported before come from the non-native .jar files still being used from the minecraft repo while the natives I replaced from my own binaries (which have a few commit differences in order to compile on arm64 and thus they aren't fully compatible). You need to load both the custom natives and non-natives in order to avoid that (which is what the MultiMC launcher does)

**Comment by JJTech0130** [comment]
Wait... So LWJGL is checking for compatibility, and deeming them incompatible, so we hot-patch it *after* the check?

**Comment by JJTech0130** [comment]
By non-native do you mean
1) Natives for x86 on aarch64 or
2) Java files not compiled for any specific arch?

**Comment by theofficialgman** [comment]
> Wait... So LWJGL is checking for compatibility, and deeming them incompatible, so we hot-patch it _after_ the check?

by non-native I mean the java files not compiled for any specific arch

no what was happening in my error report was we let gdlauncher download the jars (natives and non-natives) and then fail to launch  minecraft (since it downloads x86_64 natives)
then I added just the arm64 compiled .so files to a directory and make gdlauncher use those with the `-Djava.library.path=` but still keeping the other non-native jars from minecraft itself

that produced the errors because the non-natives jars from minecraft are "slightly" different from the ones that I compiled

**Comment by JJTech0130** [comment]
Ah ok, so can you just recompile the non-natives?

**Comment by theofficialgman** [comment]
yes I have all the non-natives recompiled in addition to the natives
everything is here: https://github.com/theofficialgman/lwjgl3-binaries-arm64
there is a branch for each lwjgl version

**Comment by JJTech0130** [comment]
so does that fix the error?

**Comment by theofficialgman** [comment]
idk... I was trying right now but gdlauncher seems to hate me and won't launch minecraft at all...
and this is all I get in my log
```
[19:24:22] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'

[19:24:24] [Render thread/INFO]: Setting user: myusername replaced for privacy
```

**Comment by theofficialgman** [comment]
> so does that fix the error?

so... I can't actually even change out the non-natives in gdlauncher because that would require adding them to the java classpath... and that seems to be generated when you click the launch button and nowhere else before that

and I can't outright replace/specify the classpath myself because then none of minecrafts own jar files (the game itself) get loaded, lol

so I think its a "can't fix" based on how gdlauncher is written

**Comment by theofficialgman** [comment]
looking at the https://github.com/r58Playz/m1-multimc-hack/blob/master/mcwrap.py m1-multimc-hack python script for inspiration, it looks like they get around this issue on M1 Macs using the official MultMC5 binary by rewriting the original classpath and arguments that multimc tries to launch
they can do this because multimc has wrapper command functionality
thats not available here in gdlauncher though so thats another dead end

**Comment by theofficialgman** [comment]
ok hear me out everyone... I have one idea that "should" work for all launchers that rely on the official minecraft version manifest.json (https://launchermeta.mojang.com/mc/game/version_manifest_v2.json or https://launchermeta.mojang.com/mc/game/version_manifest.json)

so here is what we do:
1. have a github/gitlab server mirror this version_manifest.json file and make it available for edits
2. create a .json parsing script to read each individual game version json available from the above version_manifast (so this is one minecraft version in it https://launchermeta.mojang.com/v1/packages/bcc36c0cf4cb0c8e9d6b34a62376ad7485556fe1/21w40a.json)
3. automate a  script to replace all of the `org/lwjgl` files with equivalent versions from my lwjgl binaries repos https://github.com/theofficialgman/lwjgl3-binaries-arm64, or use my multimc5 meta repo to somehow grab the information and replace it inside the microsoft provided json
4. host a new verson_manifest.json with these changes which updates automatically and just update the launchers `MC_MANIFEST_URL` at build time

**Comment by JJTech0130** [comment]
@theofficialgman I made a script to do that:
https://github.com/JJTech0130/launchermeta-parse-nodejs
Sorry for the messy code, it was like my second time with *async* js...
I never finished it cuz I figured it was not worth it when using MMC, but feel free to use it as a basis. You should remove the S3 stuff; I never got that to work.
Maybe I'll finish it sometime. Maybe.

**Comment by JJTech0130** [comment]
@theofficialgman Not sure if edited pings work, sry for the double ping.

**Comment by theofficialgman** [comment]
(edited pings don't work) but you don't need to ping me anyway, this is my issue in gdlauncher so I see every reply anyway.
Thanks for pointing me to your repo. I've never used javascript either so don't worry about it

I probably won't look into this till the weekend at earliest.. but I'll let you know if I make any progress on it.

**Comment by JJTech0130** [comment]
Not my first time with js, just my first time with *async* js, I forgot a word there :)
IIRC it mostly worked? I think it just needed to recalculate the hashes and sizes (and possibly filenames? I don't remember)...

**Comment by theofficialgman** [comment]
well in theory if I add to this script to parse from the lwjgl jars from my multimc meta repo (instead of reading from my binaries repo directly), then you don't even need to re-calculate any hashes/sizes since those are already in the multimc5 meta repo...
basically I'm just theory-crafting what would be easier to maintain for me.
Either way I'll look into it later and see what its current state is for myself

**Comment by JJTech0130** [comment]
OK! Thanks for picking this all up... I have like *way* to many projects, and they are all in different languages (this in NodeJS, my Calibre/DRM stuff in Python, my matrix stuff in Go, my FIRST Tech Challenge stuff in Java... you get the point), much too hard to keep track and I really just don't have much interest in MC on RPi anymore.

**Comment by theofficialgman** [comment]
> OK! Thanks for picking this all up...

Of course! Your documentation, repos, etc were extremely important on getting me on the right track for doing all of this, so thank you for that. Personally I don't see much reason to use Minecraft on the RPi (its a bit weak imho) but other more powerful SBC keep coming out so this should be future proof for them. I wanted minecraft java on nintendo switch in a better way than the original java launcher and a bunch of scripts so working on multimc5 just seemed like the obvious choice (given your attempts showing it could be done).

**Comment by RedstoneWizard08** [comment]
I don't know if this will help but I've successfully gotten Minecraft 1.18.2 to run in VNC on Ubuntu Server 21.10. It's possible to run it without a GPU and everything, but we now just need a launcher for it instead of a shell script that runs the literal client jar (compiled from MCP mappings).

**Comment by Eskaan** [comment]
Just noticed I never gave this one its proper labels

**Comment by theofficialgman** [comment]
just an update on this. I completed what I suggested back in october of last year https://github.com/gorilla-devs/GDLauncher/issues/727#issuecomment-941521066
I will be coming back to building GDLauncher for armhf/arm64. I have created an [automated script](https://github.com/theofficialgman/piston-meta-arm64/blob/main/mc-parse-script.sh) for generating my own custom minecraft `version_manifest.json` file to use my already existing [accompanying libraries](https://github.com/theofficialgman/lwjgl3-binaries-arm64). It uses the programs `jq` `wget` `sponge` and `spruce` to modify and merge json files.

https://github.com/theofficialgman/piston-meta-arm64
https://github.com/theofficialgman/piston-meta-arm32

This should allow any arbitrary launcher to have a simple one line change. For GDLauncher, that "should" mean simply changing this one line to my manifest
https://github.com/gorilla-devs/GDLauncher/blob/69a02964f4877f85271b5cdb09123e038c3bf9ec/src/common/utils/constants.js#L2
https://raw.githubusercontent.com/theofficialgman/piston-meta-arm64/main/mc/game/version_manifest.json

pinging @JJTech0130 just incase you wanted look

edit (see the last comment here for release binaries)

**Comment by theofficialgman** [comment]
@killpowa I have rebased the ARM64 changes that were posted earlier and applied them to my fork. however, I still can't build with seemingly non-arm64 issues https://github.com/theofficialgman/GDLauncher

I always get this error (regardless if I use npm i or yarn). `npm i` completes without error, then I get this when running `npm run release:setup`
```
 npm run release:setup

> gdlauncher@1.1.29 release:setup
> cross-env-shell NODE_ENV=production APP_TYPE=electron REACT_APP_RELEASE_TYPE=setup "npm run build" && npm run build-electron:setup && npm run deploy setup


> gdlauncher@1.1.29 build
> cross-env-shell NODE_ENV=production APP_TYPE=electron CI=false craco build

craco:  *** Cannot find ESLint plugin (ESLintWebpackPlugin). ***
Creating an optimized production build...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/home/garrett/GDLauncher/node_modules/react-scripts/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/garrett/GDLauncher/node_modules/react-scripts/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/garrett/GDLauncher/node_modules/react-scripts/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/garrett/GDLauncher/node_modules/react-scripts/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/garrett/GDLauncher/node_modules/react-scripts/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/garrett/GDLauncher/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/garrett/GDLauncher/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/garrett/GDLauncher/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/garrett/GDLauncher/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/garrett/GDLauncher/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/garrett/GDLauncher/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/garrett/GDLauncher/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/garrett/GDLauncher/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/garrett/GDLauncher/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/home/garrett/GDLauncher/node_modules/react-scripts/scripts/build.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/home/garrett/GDLauncher/node_modules/react-scripts/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/garrett/GDLauncher/node_modules/react-scripts/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/garrett/GDLauncher/node_modules/react-scripts/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/garrett/GDLauncher/node_modules/react-scripts/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/garrett/GDLauncher/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/garrett/GDLauncher/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/garrett/GDLauncher/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/garrett/GDLauncher/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.9.0
```

**Comment by theofficialgman** [comment]
ok I manged to build... but I am getting errors on creating/selecting an instance
```
actions.js:2911 Missing resource: /home/garrett/.config/gdlauncher_next/datastore/libraries/net/minecraft/1.12.2.jar
actions.js:1132 Error: EEXIST: file already exists, open '/home/garrett/.config/gdlauncher_next/instances/1.12.2/installing.lock'
actions.js:2236 TypeError: The "path" argument must be of type string. Received undefined
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:120:11)
    at Object.join (node:path:1172:7)
    at index.js:143:24
    at Array.reduce (<anonymous>)
    at L (index.js:111:8)
    at actions.js:2178:25
    at f (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.next (regeneratorRuntime.js:117:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

edit: oh oops its my meta. looks like the format is slightly different than MMC

**Comment by theofficialgman** [comment]
fixed the meta
everything works!

![Screenshot from 2022-09-06 21-47-36](https://user-images.githubusercontent.com/28281419/188770843-96b4c719-0425-47ab-aeba-33b990ab4109.png)

**Comment by theofficialgman** [comment]
you can download my release binaries for ARM32 and ARM64 linux from here:
https://github.com/Pi-Apps-Coders/files/releases/tag/large-files

everything (including the java downloader) works.
Tested on Nintendo Switch, Jetson Orin, and Raspberry Pi
