### ISSUE TITLE
Fabric modpacks won't download anymore

### ISSUE THREAD

**Issue by jinkhya** [gorilla-devs/GDLauncher#743]
**Describe the bug**
When I try to download All of fabric 3 it gets stuck at "Downloading game files... 100%"

**To Reproduce**
1. Try to download AOF3 (or any fabric pack)

**Expected behavior**
I expect it to download completly :)

**Screenshots**
https://i.imgur.com/wcxxORj.png

**Operating System:**
 - OS: Linux - Manjaro 
 - kernel 5.10.2-2

**Additional context**

**Comment by DetermineAbsurd** [comment]
Error is present in stable and beta build with the following in the error log:

```
webpack-internal:///4:7 Uncaught (in promise) TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112)
    at Object.join (path.js:375)
    at _callee28$ (webpack-internal:///33:198)
    at tryCatch (webpack-internal:///482:64)
    at Generator.invoke [as _invoke] (webpack-internal:///482:281)
    at Generator.eval [as next] (webpack-internal:///482:117)
    at asyncGeneratorStep (webpack-internal:///4:4)
    at _next (webpack-internal:///4:26)
    at eval (webpack-internal:///4:33)
    at new Promise (<anonymous>)
NodeError @ internal/errors.js:216
validateString @ internal/validators.js:112
join @ path.js:375
_callee28$ @ webpack-internal:///33:198
tryCatch @ webpack-internal:///482:64
invoke @ webpack-internal:///482:281
eval @ webpack-internal:///482:117
asyncGeneratorStep @ webpack-internal:///4:4
_next @ webpack-internal:///4:26
eval @ webpack-internal:///4:33
eval @ webpack-internal:///4:22
eval @ webpack-internal:///33:204
eval @ webpack-internal:///1028:50
dispatch @ webpack-internal:///43:635
_callee31$ @ webpack-internal:///33:206
tryCatch @ webpack-internal:///482:64
invoke @ webpack-internal:///482:281
eval @ webpack-internal:///482:117
asyncGeneratorStep @ webpack-internal:///4:4
_next @ webpack-internal:///4:26
```

**Comment by irunatbullets** [comment]
Forge removed a bunch of forge versions that had game breaking bugs from their https://files.minecraftforge.net/maven/net/minecraftforge/forge/maven-metadata.json (which is what GDlauncher uses to find valid versions of forge).

AOF will release their next pack with an updated version of the forge modloader. This will mean that all previous version 2.5.x won't be available to install using the create instance from twitch/curse option in GDlauncher 

To get 2.5.x versions of All Of Fabric 3 working you'll need to:

- download the zip from curseforge
- unzip the file
- open manifest.json
- change where it says at the top 35.0.17 to 35.0.14
- zip everything back up
- install the instance from the edited zip file.

I wonder if GDlauncher is allowed to use this endpoint (or perhaps there's a newer non-twitch one) for getting version info from curseforge https://twitchappapi.docs.apiary.io/#/reference/0/get-modloader-info - as curseforge appears to have their own repo for forge versions, and it feels a little safer for fabric modpacks - which only use forge modloader for jumploader.

Would that be a significant rework for GDlauncher? Or possible at all because it's a first-party API?

**Comment by irunatbullets** [comment]
AOF 3 2.5.8 has been released today with a fix for this issue.

**Comment by lonevox** [comment]
I'm getting this issue with both Forge and Fabric modpacks from Curseforge (including when I download a zip of the modpack and manually add an instance). I also get "The "path" argument must be of type string" error.

**Comment by jakecolon3** [comment]
Getting the same error while downloading Stoneblock 2 from both curseforge and ftb, am on beta branch.

**Comment by lonevox** [comment]
This is fixed in 1.1.5

**Comment by chrsrns** [comment]
I can confirm that this problem still exists; particularly with [[FABRIC] Adventure Pack](https://www.curseforge.com/minecraft/modpacks/fabric-adventure-pack).

**Comment by urmet** [comment]
that's a different issue, fixed in next release. #961

**Comment by Memeologisty** [comment]
Getting the issue now on [All of Fabric 4 - 1.17.1](https://www.curseforge.com/minecraft/modpacks/all-of-fabric-4)

**Comment by urmet** [comment]
look at previous comment.

**Comment by Eskaan** [comment]
> Getting the issue now on [All of Fabric 4 - 1.17.1](https://www.curseforge.com/minecraft/modpacks/all-of-fabric-4)

Please. You don’t have to check this for every Modpack. This issue is known. We got a merged fix.
